version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UBUNTU_USER=${UBUNTU_USER}
        - UBUNTU_GROUP=${UBUNTU_GROUP}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./meta/database:/var/lib/postgresql/data  

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./meta/pgadmin:/pgadmin

